### PR TITLE
Changes to match the packaging rework

### PR DESCRIPTION
**Pull request by Antiz96**
Hey,

Changes to match the recent rework on the packages side of things:

**grub**: Deleted `grub` since we now provide the Crystal's specific grub stuff via the `grub-theme` package instead of re-packaging `grub` completely.  

**zramd**: Switched the source from `pkg` to `aur`. Since we stated the addition we initially made a custom PKGBUILD for is unnecessary we can drop the said custom PKGBUILD from our repo and just grab `zramd` from the [AUR](https://aur.archlinux.org/packages/zramd).

**caffeine**: Switched the source from `gse` to `age`. Since the [v42 release](https://github.com/eonpatapon/gnome-shell-extension-caffeine/releases/tag/v42) that came out a few day ago brings [support for Gnome 43](https://github.com/eonpatapon/gnome-shell-extension-caffeine/commit/e5b2fe7bdf2ad6ee090125d64bcc037ed81b4a08) we can drop our custom PKGBUILD and just grab `gnome-shell-extension-caffeine` from the [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-caffeine) (which I maintain :smile:).

**desktop-icons-neo**: Switched the source from `gse` to `age`. Since `gnome-shell-extension-desktop-icons-neo` is now available on the AUR, we can drop our PKGBUILD and just grab it from the [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-desktop-icons-neo) (which I maintain as well :smile:). 
*By the way, Michal said `desktop-icons-neo` will be soon dropped from Onyx? If that's so, should I just delete the associated entry instead? I'll make a new commit in that sense if needed.*

**base**: Deleted `base` since we now provide the Crystal's specific core packages via the `crystal-core` package instead of re-packaging `base` completely.

**filesystem**: Deleted `filesystem` since we now provide the Crystal's specific files via the `crystal-branding` package instead of re-packaging `filesystem` completely.

**lsb-release**:  Deleted `lsb-release` since our custom PKGBUILD have no purpose :sweat_smile: (it modifies a file that actually have no use whatsoever).

**onyx**: Deleted the duplicate entry.

**pfetch**: Deleted `pfetch` since we agreed having `neofetch` is enough.

**jade-tui**: Added `jade-tui` since it wasn't there already.
*Was this intended? If so I'll remove it through a new commit if needed*

**crystal-core**: Added `crystal-core`.

**crystal-branding**: Adeed `crystal-branding`.

We could then drop the following PKGBUILD and their associated repo from the packages GH organisation:
- zramd
- gnome-shell-extension-desktop-icons-neo
- gnome-shell-extension-desktop-caffeine
- filesystem
- pfetch
- base
- lsb-release
- grub

On a side note, maybe we could take advantage of this PR to also make a bit of cleaning in our repositories (e.g. delete the dropped packages from it like `grub`, `base`, etc... and maybe delete some old versions of packages like `amethyst-3.6.0`)?

What do you think?

### CODE REVIEW

**Review by SomethingGeneric — APPROVED** [review]
LGTM

**Comment by SomethingGeneric** [comment]
I hope that the allow downgrades intervention will also leave them with a working GRUB too, since we're also dropping that

**Comment by Antiz96** [comment]
> I hope that the allow downgrades intervention will also leave them with a working GRUB too, since we're also dropping that

I would say it should. 
But if it does not, we would *only* need to add a `sudo grub install [...] && sudo grub-mkconfig -o /boot/grub/grub.cfg` to the manual intervention.

**Comment by Antiz96** [comment]
@SomethingGeneric @not-my-segfault 
BTW, before we merge this PR we might want to merge this one: https://github.com/crystal-linux-packages/crystal-core/pull/1
Otherwise, `malachite` won't be able to find `crystal-core`.

EDIT: done

**Review by mchalunderscore — APPROVED** [review]

**Pull request merged**
